// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhqrsjawpuajbvkamwwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocXJzamF3cHVhamJ2a2Ftd3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDc3MjMsImV4cCI6MjA2NzIyMzcyM30.grnW0L0QGuBXAJ2_OdNMYDiJcMak7EcjNNK_Ji9c0pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});